-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Interface.TeamAuditEntryData exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onOrgRestoreMemberMembershipTeamAuditEntryData : SelectionSet decodesTo Api.GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
    , onTeamAddMemberAuditEntry : SelectionSet decodesTo Api.GitHub.Object.TeamAddMemberAuditEntry
    , onTeamAddRepositoryAuditEntry : SelectionSet decodesTo Api.GitHub.Object.TeamAddRepositoryAuditEntry
    , onTeamChangeParentTeamAuditEntry : SelectionSet decodesTo Api.GitHub.Object.TeamChangeParentTeamAuditEntry
    , onTeamRemoveMemberAuditEntry : SelectionSet decodesTo Api.GitHub.Object.TeamRemoveMemberAuditEntry
    , onTeamRemoveRepositoryAuditEntry : SelectionSet decodesTo Api.GitHub.Object.TeamRemoveRepositoryAuditEntry
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Api.GitHub.Interface.TeamAuditEntryData
fragments selections =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "OrgRestoreMemberMembershipTeamAuditEntryData" selections.onOrgRestoreMemberMembershipTeamAuditEntryData
        , Object.buildFragment "TeamAddMemberAuditEntry" selections.onTeamAddMemberAuditEntry
        , Object.buildFragment "TeamAddRepositoryAuditEntry" selections.onTeamAddRepositoryAuditEntry
        , Object.buildFragment "TeamChangeParentTeamAuditEntry" selections.onTeamChangeParentTeamAuditEntry
        , Object.buildFragment "TeamRemoveMemberAuditEntry" selections.onTeamRemoveMemberAuditEntry
        , Object.buildFragment "TeamRemoveRepositoryAuditEntry" selections.onTeamRemoveRepositoryAuditEntry
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onOrgRestoreMemberMembershipTeamAuditEntryData = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamAddMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamAddRepositoryAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamChangeParentTeamAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamRemoveMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamRemoveRepositoryAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The team associated with the action
-}
team : SelectionSet decodesTo Api.GitHub.Object.Team -> SelectionSet (Maybe decodesTo) Api.GitHub.Interface.TeamAuditEntryData
team object_ =
    Object.selectionForCompositeField "team" [] object_ (identity >> Decode.nullable)


{-| The name of the team
-}
teamName : SelectionSet (Maybe String) Api.GitHub.Interface.TeamAuditEntryData
teamName =
    Object.selectionForField "(Maybe String)" "teamName" [] (Decode.string |> Decode.nullable)


{-| The HTTP path for this team
-}
teamResourcePath : SelectionSet (Maybe Api.GitHub.ScalarCodecs.Uri) Api.GitHub.Interface.TeamAuditEntryData
teamResourcePath =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "teamResourcePath" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)


{-| The HTTP URL for this team
-}
teamUrl : SelectionSet (Maybe Api.GitHub.ScalarCodecs.Uri) Api.GitHub.Interface.TeamAuditEntryData
teamUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "teamUrl" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
