module VerifyExamples.Application.I18n.T1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Application.I18n exposing (..)
import Application.I18n exposing (t_)
import Dict as Dict exposing (Dict)
import Json.Decode as Decode
import I18Next



fakeTranslations : Dict String I18Next.Translations
fakeTranslations = Dict.fromList
    [ ("en", fakeEnTranslations)
    , ("fr", fakeFrTranslations)
    ]
fakeEnTranslations : I18Next.Translations
fakeEnTranslations =
    case Decode.decodeString I18Next.translationsDecoder "{ \"greet\": \"Hello\", \"goodbye\": \"Goodbye\" }" of
        Ok t -> t
        Err _ -> I18Next.initialTranslations
fakeFrTranslations : I18Next.Translations
fakeFrTranslations =
    case Decode.decodeString I18Next.translationsDecoder "{ \"greet\": \"Bonjour\" }" of
        Ok t -> t
        Err _ -> I18Next.initialTranslations



spec1 : Test.Test
spec1 =
    Test.test "#t: \n\n    t \"fr\" fakeTranslations { k = \"goodbye\", default = \"Different goodbye\" }\n    --> \"Goodbye\"" <|
        \() ->
            Expect.equal
                (
                t "fr" fakeTranslations { k = "goodbye", default = "Different goodbye" }
                )
                (
                "Goodbye"
                )