-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.ActorLocation exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| City
-}
city : SelectionSet (Maybe String) Api.GitHub.Object.ActorLocation
city =
    Object.selectionForField "(Maybe String)" "city" [] (Decode.string |> Decode.nullable)


{-| Country name
-}
country : SelectionSet (Maybe String) Api.GitHub.Object.ActorLocation
country =
    Object.selectionForField "(Maybe String)" "country" [] (Decode.string |> Decode.nullable)


{-| Country code
-}
countryCode : SelectionSet (Maybe String) Api.GitHub.Object.ActorLocation
countryCode =
    Object.selectionForField "(Maybe String)" "countryCode" [] (Decode.string |> Decode.nullable)


{-| Region name
-}
region : SelectionSet (Maybe String) Api.GitHub.Object.ActorLocation
region =
    Object.selectionForField "(Maybe String)" "region" [] (Decode.string |> Decode.nullable)


{-| Region or state code
-}
regionCode : SelectionSet (Maybe String) Api.GitHub.Object.ActorLocation
regionCode =
    Object.selectionForField "(Maybe String)" "regionCode" [] (Decode.string |> Decode.nullable)
