-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.ContributionCalendar exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of hex color codes used in this calendar. The darker the color, the more contributions it represents.
-}
colors : SelectionSet (List String) Api.GitHub.Object.ContributionCalendar
colors =
    Object.selectionForField "(List String)" "colors" [] (Decode.string |> Decode.list)


{-| Determine if the color set was chosen because it's currently Halloween.
-}
isHalloween : SelectionSet Bool Api.GitHub.Object.ContributionCalendar
isHalloween =
    Object.selectionForField "Bool" "isHalloween" [] Decode.bool


{-| A list of the months of contributions in this calendar.
-}
months : SelectionSet decodesTo Api.GitHub.Object.ContributionCalendarMonth -> SelectionSet (List decodesTo) Api.GitHub.Object.ContributionCalendar
months object_ =
    Object.selectionForCompositeField "months" [] object_ (identity >> Decode.list)


{-| The count of total contributions in the calendar.
-}
totalContributions : SelectionSet Int Api.GitHub.Object.ContributionCalendar
totalContributions =
    Object.selectionForField "Int" "totalContributions" [] Decode.int


{-| A list of the weeks of contributions in this calendar.
-}
weeks : SelectionSet decodesTo Api.GitHub.Object.ContributionCalendarWeek -> SelectionSet (List decodesTo) Api.GitHub.Object.ContributionCalendar
weeks object_ =
    Object.selectionForCompositeField "weeks" [] object_ (identity >> Decode.list)
