-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.ContributionCalendarDay exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The hex color code that represents how many contributions were made on this day compared to others in the calendar.
-}
color : SelectionSet String Api.GitHub.Object.ContributionCalendarDay
color =
    Object.selectionForField "String" "color" [] Decode.string


{-| How many contributions were made by the user on this day.
-}
contributionCount : SelectionSet Int Api.GitHub.Object.ContributionCalendarDay
contributionCount =
    Object.selectionForField "Int" "contributionCount" [] Decode.int


{-| The day this square represents.
-}
date : SelectionSet Api.GitHub.ScalarCodecs.Date Api.GitHub.Object.ContributionCalendarDay
date =
    Object.selectionForField "ScalarCodecs.Date" "date" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecDate |> .decoder)


{-| A number representing which day of the week this square represents, e.g., 1 is Monday.
-}
weekday : SelectionSet Int Api.GitHub.Object.ContributionCalendarDay
weekday =
    Object.selectionForField "Int" "weekday" [] Decode.int
