-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.EnterpriseServerUserAccountsUpload exposing (..)

import Api.GitHub.Enum.EnterpriseServerUserAccountsUploadSyncState
import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.GitHub.ScalarCodecs.DateTime Api.GitHub.Object.EnterpriseServerUserAccountsUpload
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The enterprise to which this upload belongs.
-}
enterprise : SelectionSet decodesTo Api.GitHub.Object.Enterprise -> SelectionSet decodesTo Api.GitHub.Object.EnterpriseServerUserAccountsUpload
enterprise object_ =
    Object.selectionForCompositeField "enterprise" [] object_ identity


{-| The Enterprise Server installation for which this upload was generated.
-}
enterpriseServerInstallation : SelectionSet decodesTo Api.GitHub.Object.EnterpriseServerInstallation -> SelectionSet decodesTo Api.GitHub.Object.EnterpriseServerUserAccountsUpload
enterpriseServerInstallation object_ =
    Object.selectionForCompositeField "enterpriseServerInstallation" [] object_ identity


id : SelectionSet Api.GitHub.ScalarCodecs.Id Api.GitHub.Object.EnterpriseServerUserAccountsUpload
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the file uploaded.
-}
name : SelectionSet String Api.GitHub.Object.EnterpriseServerUserAccountsUpload
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The synchronization state of the upload
-}
syncState : SelectionSet Api.GitHub.Enum.EnterpriseServerUserAccountsUploadSyncState.EnterpriseServerUserAccountsUploadSyncState Api.GitHub.Object.EnterpriseServerUserAccountsUpload
syncState =
    Object.selectionForField "Enum.EnterpriseServerUserAccountsUploadSyncState.EnterpriseServerUserAccountsUploadSyncState" "syncState" [] Api.GitHub.Enum.EnterpriseServerUserAccountsUploadSyncState.decoder


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Api.GitHub.ScalarCodecs.DateTime Api.GitHub.Object.EnterpriseServerUserAccountsUpload
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
