-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.ExternalIdentity exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The GUID for this identity
-}
guid : SelectionSet String Api.GitHub.Object.ExternalIdentity
guid =
    Object.selectionForField "String" "guid" [] Decode.string


id : SelectionSet Api.GitHub.ScalarCodecs.Id Api.GitHub.Object.ExternalIdentity
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Organization invitation for this SCIM-provisioned external identity
-}
organizationInvitation : SelectionSet decodesTo Api.GitHub.Object.OrganizationInvitation -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ExternalIdentity
organizationInvitation object_ =
    Object.selectionForCompositeField "organizationInvitation" [] object_ (identity >> Decode.nullable)


{-| SAML Identity attributes
-}
samlIdentity : SelectionSet decodesTo Api.GitHub.Object.ExternalIdentitySamlAttributes -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ExternalIdentity
samlIdentity object_ =
    Object.selectionForCompositeField "samlIdentity" [] object_ (identity >> Decode.nullable)


{-| SCIM Identity attributes
-}
scimIdentity : SelectionSet decodesTo Api.GitHub.Object.ExternalIdentityScimAttributes -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ExternalIdentity
scimIdentity object_ =
    Object.selectionForCompositeField "scimIdentity" [] object_ (identity >> Decode.nullable)


{-| User linked to this external identity. Will be NULL if this identity has not been claimed by an organization member.
-}
user : SelectionSet decodesTo Api.GitHub.Object.User -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ExternalIdentity
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)
