-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.RepositoryCollaboratorEdge exposing (..)

import Api.GitHub.Enum.RepositoryPermission
import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A cursor for use in pagination.
-}
cursor : SelectionSet String Api.GitHub.Object.RepositoryCollaboratorEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


node : SelectionSet decodesTo Api.GitHub.Object.User -> SelectionSet decodesTo Api.GitHub.Object.RepositoryCollaboratorEdge
node object_ =
    Object.selectionForCompositeField "node" [] object_ identity


{-| The permission the user has on the repository.
-}
permission : SelectionSet Api.GitHub.Enum.RepositoryPermission.RepositoryPermission Api.GitHub.Object.RepositoryCollaboratorEdge
permission =
    Object.selectionForField "Enum.RepositoryPermission.RepositoryPermission" "permission" [] Api.GitHub.Enum.RepositoryPermission.decoder


{-| A list of sources for the user's access to the repository.
-}
permissionSources : SelectionSet decodesTo Api.GitHub.Object.PermissionSource -> SelectionSet (Maybe (List decodesTo)) Api.GitHub.Object.RepositoryCollaboratorEdge
permissionSources object_ =
    Object.selectionForCompositeField "permissionSources" [] object_ (identity >> Decode.list >> Decode.nullable)
