-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Object.ReviewDismissedEvent exposing (..)

import Api.GitHub.Enum.PullRequestReviewState
import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the actor who performed the event.
-}
actor : SelectionSet decodesTo Api.GitHub.Interface.Actor -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ReviewDismissedEvent
actor object_ =
    Object.selectionForCompositeField "actor" [] object_ (identity >> Decode.nullable)


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.GitHub.ScalarCodecs.DateTime Api.GitHub.Object.ReviewDismissedEvent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Api.GitHub.Object.ReviewDismissedEvent
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| Identifies the optional message associated with the 'review\_dismissed' event.
-}
dismissalMessage : SelectionSet (Maybe String) Api.GitHub.Object.ReviewDismissedEvent
dismissalMessage =
    Object.selectionForField "(Maybe String)" "dismissalMessage" [] (Decode.string |> Decode.nullable)


{-| Identifies the optional message associated with the event, rendered to HTML.
-}
dismissalMessageHTML : SelectionSet (Maybe String) Api.GitHub.Object.ReviewDismissedEvent
dismissalMessageHTML =
    Object.selectionForField "(Maybe String)" "dismissalMessageHTML" [] (Decode.string |> Decode.nullable)


id : SelectionSet Api.GitHub.ScalarCodecs.Id Api.GitHub.Object.ReviewDismissedEvent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Identifies the previous state of the review with the 'review\_dismissed' event.
-}
previousReviewState : SelectionSet Api.GitHub.Enum.PullRequestReviewState.PullRequestReviewState Api.GitHub.Object.ReviewDismissedEvent
previousReviewState =
    Object.selectionForField "Enum.PullRequestReviewState.PullRequestReviewState" "previousReviewState" [] Api.GitHub.Enum.PullRequestReviewState.decoder


{-| PullRequest referenced by event.
-}
pullRequest : SelectionSet decodesTo Api.GitHub.Object.PullRequest -> SelectionSet decodesTo Api.GitHub.Object.ReviewDismissedEvent
pullRequest object_ =
    Object.selectionForCompositeField "pullRequest" [] object_ identity


{-| Identifies the commit which caused the review to become stale.
-}
pullRequestCommit : SelectionSet decodesTo Api.GitHub.Object.PullRequestCommit -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ReviewDismissedEvent
pullRequestCommit object_ =
    Object.selectionForCompositeField "pullRequestCommit" [] object_ (identity >> Decode.nullable)


{-| The HTTP path for this review dismissed event.
-}
resourcePath : SelectionSet Api.GitHub.ScalarCodecs.Uri Api.GitHub.Object.ReviewDismissedEvent
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| Identifies the review associated with the 'review\_dismissed' event.
-}
review : SelectionSet decodesTo Api.GitHub.Object.PullRequestReview -> SelectionSet (Maybe decodesTo) Api.GitHub.Object.ReviewDismissedEvent
review object_ =
    Object.selectionForCompositeField "review" [] object_ (identity >> Decode.nullable)


{-| The HTTP URL for this review dismissed event.
-}
url : SelectionSet Api.GitHub.ScalarCodecs.Uri Api.GitHub.Object.ReviewDismissedEvent
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.GitHub.ScalarCodecs.codecs |> Api.GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder)
