module VerifyExamples.Core.I18n.T0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Core.I18n exposing (..)
import Core.I18n.Types exposing (Language(..))
import Core.I18n exposing (t_)
import Dict as Dict exposing (Dict)
import Json.Decode as Decode
import I18Next



fakeTranslations : Dict String I18Next.Translations
fakeTranslations = Dict.fromList
    [ ("en", fakeEnTranslations)
    , ("fr", fakeFrTranslations)
    ]
fakeEnTranslations : I18Next.Translations
fakeEnTranslations =
    case Decode.decodeString I18Next.translationsDecoder "{ \"greet\": \"Hello\", \"goodbye\": \"Goodbye\" }" of
        Ok t -> t
        Err _ -> I18Next.initialTranslations
fakeFrTranslations : I18Next.Translations
fakeFrTranslations =
    case Decode.decodeString I18Next.translationsDecoder "{ \"greet\": \"Bonjour\" }" of
        Ok t -> t
        Err _ -> I18Next.initialTranslations



spec0 : Test.Test
spec0 =
    Test.test "#t: \n\n    t (Language \"fr\") fakeTranslations { k = \"wrongGoodbye\", default = \"Different goodbye\" }\n    --> \"Different goodbye\"" <|
        \() ->
            Expect.equal
                (
                t (Language "fr") fakeTranslations { k = "wrongGoodbye", default = "Different goodbye" }
                )
                (
                "Different goodbye"
                )