module VerifyExamples.Core.I18n.T_0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Core.I18n exposing (..)
import Json.Decode as Decode
import I18Next



fakeTranslations : I18Next.Translations
fakeTranslations =
    case Decode.decodeString I18Next.translationsDecoder "{ \"greet\": \"Hello\" }" of
        Ok t -> t
        Err _ -> I18Next.initialTranslations



spec0 : Test.Test
spec0 =
    Test.test "#t_: \n\n    t_ fakeTranslations { k = \"wrongGreet\", default = \"Goodbye\" }\n    --> \"Goodbye\"" <|
        \() ->
            Expect.equal
                (
                t_ fakeTranslations { k = "wrongGreet", default = "Goodbye" }
                )
                (
                "Goodbye"
                )