-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Union.OrgRestoreMemberAuditEntryMembership exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onOrgRestoreMemberMembershipOrganizationAuditEntryData : SelectionSet decodesTo Api.GitHub.Object.OrgRestoreMemberMembershipOrganizationAuditEntryData
    , onOrgRestoreMemberMembershipRepositoryAuditEntryData : SelectionSet decodesTo Api.GitHub.Object.OrgRestoreMemberMembershipRepositoryAuditEntryData
    , onOrgRestoreMemberMembershipTeamAuditEntryData : SelectionSet decodesTo Api.GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
    }


{-| Build up a selection for this Union by passing in a Fragments record.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Api.GitHub.Union.OrgRestoreMemberAuditEntryMembership
fragments selections =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "OrgRestoreMemberMembershipOrganizationAuditEntryData" selections.onOrgRestoreMemberMembershipOrganizationAuditEntryData
        , Object.buildFragment "OrgRestoreMemberMembershipRepositoryAuditEntryData" selections.onOrgRestoreMemberMembershipRepositoryAuditEntryData
        , Object.buildFragment "OrgRestoreMemberMembershipTeamAuditEntryData" selections.onOrgRestoreMemberMembershipTeamAuditEntryData
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onOrgRestoreMemberMembershipOrganizationAuditEntryData = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRestoreMemberMembershipRepositoryAuditEntryData = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRestoreMemberMembershipTeamAuditEntryData = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }
