-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.GitHub.Mutation exposing (..)

import Api.GitHub.InputObject
import Api.GitHub.Interface
import Api.GitHub.Object
import Api.GitHub.Scalar
import Api.GitHub.ScalarCodecs
import Api.GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AcceptEnterpriseAdministratorInvitationRequiredArguments =
    { input : Api.GitHub.InputObject.AcceptEnterpriseAdministratorInvitationInput }


{-| Accepts a pending invitation for a user to become an administrator of an enterprise.
-}
acceptEnterpriseAdministratorInvitation : AcceptEnterpriseAdministratorInvitationRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AcceptEnterpriseAdministratorInvitationPayload -> SelectionSet (Maybe decodesTo) RootMutation
acceptEnterpriseAdministratorInvitation requiredArgs object_ =
    Object.selectionForCompositeField "acceptEnterpriseAdministratorInvitation" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAcceptEnterpriseAdministratorInvitationInput ] object_ (identity >> Decode.nullable)


type alias AcceptTopicSuggestionRequiredArguments =
    { input : Api.GitHub.InputObject.AcceptTopicSuggestionInput }


{-| Applies a suggested topic to the repository.
-}
acceptTopicSuggestion : AcceptTopicSuggestionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AcceptTopicSuggestionPayload -> SelectionSet (Maybe decodesTo) RootMutation
acceptTopicSuggestion requiredArgs object_ =
    Object.selectionForCompositeField "acceptTopicSuggestion" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAcceptTopicSuggestionInput ] object_ (identity >> Decode.nullable)


type alias AddAssigneesToAssignableRequiredArguments =
    { input : Api.GitHub.InputObject.AddAssigneesToAssignableInput }


{-| Adds assignees to an assignable object.
-}
addAssigneesToAssignable : AddAssigneesToAssignableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddAssigneesToAssignablePayload -> SelectionSet (Maybe decodesTo) RootMutation
addAssigneesToAssignable requiredArgs object_ =
    Object.selectionForCompositeField "addAssigneesToAssignable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddAssigneesToAssignableInput ] object_ (identity >> Decode.nullable)


type alias AddCommentRequiredArguments =
    { input : Api.GitHub.InputObject.AddCommentInput }


{-| Adds a comment to an Issue or Pull Request.
-}
addComment : AddCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
addComment requiredArgs object_ =
    Object.selectionForCompositeField "addComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddCommentInput ] object_ (identity >> Decode.nullable)


type alias AddLabelsToLabelableRequiredArguments =
    { input : Api.GitHub.InputObject.AddLabelsToLabelableInput }


{-| Adds labels to a labelable object.
-}
addLabelsToLabelable : AddLabelsToLabelableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddLabelsToLabelablePayload -> SelectionSet (Maybe decodesTo) RootMutation
addLabelsToLabelable requiredArgs object_ =
    Object.selectionForCompositeField "addLabelsToLabelable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddLabelsToLabelableInput ] object_ (identity >> Decode.nullable)


type alias AddProjectCardRequiredArguments =
    { input : Api.GitHub.InputObject.AddProjectCardInput }


{-| Adds a card to a ProjectColumn. Either `contentId` or `note` must be provided but **not** both.
-}
addProjectCard : AddProjectCardRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddProjectCardPayload -> SelectionSet (Maybe decodesTo) RootMutation
addProjectCard requiredArgs object_ =
    Object.selectionForCompositeField "addProjectCard" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddProjectCardInput ] object_ (identity >> Decode.nullable)


type alias AddProjectColumnRequiredArguments =
    { input : Api.GitHub.InputObject.AddProjectColumnInput }


{-| Adds a column to a Project.
-}
addProjectColumn : AddProjectColumnRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddProjectColumnPayload -> SelectionSet (Maybe decodesTo) RootMutation
addProjectColumn requiredArgs object_ =
    Object.selectionForCompositeField "addProjectColumn" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddProjectColumnInput ] object_ (identity >> Decode.nullable)


type alias AddPullRequestReviewRequiredArguments =
    { input : Api.GitHub.InputObject.AddPullRequestReviewInput }


{-| Adds a review to a Pull Request.
-}
addPullRequestReview : AddPullRequestReviewRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddPullRequestReviewPayload -> SelectionSet (Maybe decodesTo) RootMutation
addPullRequestReview requiredArgs object_ =
    Object.selectionForCompositeField "addPullRequestReview" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddPullRequestReviewInput ] object_ (identity >> Decode.nullable)


type alias AddPullRequestReviewCommentRequiredArguments =
    { input : Api.GitHub.InputObject.AddPullRequestReviewCommentInput }


{-| Adds a comment to a review.
-}
addPullRequestReviewComment : AddPullRequestReviewCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddPullRequestReviewCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
addPullRequestReviewComment requiredArgs object_ =
    Object.selectionForCompositeField "addPullRequestReviewComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddPullRequestReviewCommentInput ] object_ (identity >> Decode.nullable)


type alias AddReactionRequiredArguments =
    { input : Api.GitHub.InputObject.AddReactionInput }


{-| Adds a reaction to a subject.
-}
addReaction : AddReactionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddReactionPayload -> SelectionSet (Maybe decodesTo) RootMutation
addReaction requiredArgs object_ =
    Object.selectionForCompositeField "addReaction" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddReactionInput ] object_ (identity >> Decode.nullable)


type alias AddStarRequiredArguments =
    { input : Api.GitHub.InputObject.AddStarInput }


{-| Adds a star to a Starrable.
-}
addStar : AddStarRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.AddStarPayload -> SelectionSet (Maybe decodesTo) RootMutation
addStar requiredArgs object_ =
    Object.selectionForCompositeField "addStar" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeAddStarInput ] object_ (identity >> Decode.nullable)


type alias ArchiveRepositoryRequiredArguments =
    { input : Api.GitHub.InputObject.ArchiveRepositoryInput }


{-| Marks a repository as archived.
-}
archiveRepository : ArchiveRepositoryRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ArchiveRepositoryPayload -> SelectionSet (Maybe decodesTo) RootMutation
archiveRepository requiredArgs object_ =
    Object.selectionForCompositeField "archiveRepository" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeArchiveRepositoryInput ] object_ (identity >> Decode.nullable)


type alias CancelEnterpriseAdminInvitationRequiredArguments =
    { input : Api.GitHub.InputObject.CancelEnterpriseAdminInvitationInput }


{-| Cancels a pending invitation for an administrator to join an enterprise.
-}
cancelEnterpriseAdminInvitation : CancelEnterpriseAdminInvitationRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CancelEnterpriseAdminInvitationPayload -> SelectionSet (Maybe decodesTo) RootMutation
cancelEnterpriseAdminInvitation requiredArgs object_ =
    Object.selectionForCompositeField "cancelEnterpriseAdminInvitation" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCancelEnterpriseAdminInvitationInput ] object_ (identity >> Decode.nullable)


type alias ChangeUserStatusRequiredArguments =
    { input : Api.GitHub.InputObject.ChangeUserStatusInput }


{-| Update your status on GitHub.
-}
changeUserStatus : ChangeUserStatusRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ChangeUserStatusPayload -> SelectionSet (Maybe decodesTo) RootMutation
changeUserStatus requiredArgs object_ =
    Object.selectionForCompositeField "changeUserStatus" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeChangeUserStatusInput ] object_ (identity >> Decode.nullable)


type alias ClearLabelsFromLabelableRequiredArguments =
    { input : Api.GitHub.InputObject.ClearLabelsFromLabelableInput }


{-| Clears all labels from a labelable object.
-}
clearLabelsFromLabelable : ClearLabelsFromLabelableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ClearLabelsFromLabelablePayload -> SelectionSet (Maybe decodesTo) RootMutation
clearLabelsFromLabelable requiredArgs object_ =
    Object.selectionForCompositeField "clearLabelsFromLabelable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeClearLabelsFromLabelableInput ] object_ (identity >> Decode.nullable)


type alias CloneProjectRequiredArguments =
    { input : Api.GitHub.InputObject.CloneProjectInput }


{-| Creates a new project by cloning configuration from an existing project.
-}
cloneProject : CloneProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CloneProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
cloneProject requiredArgs object_ =
    Object.selectionForCompositeField "cloneProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCloneProjectInput ] object_ (identity >> Decode.nullable)


type alias CloneTemplateRepositoryRequiredArguments =
    { input : Api.GitHub.InputObject.CloneTemplateRepositoryInput }


{-| Create a new repository with the same files and directory structure as a template repository.
-}
cloneTemplateRepository : CloneTemplateRepositoryRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CloneTemplateRepositoryPayload -> SelectionSet (Maybe decodesTo) RootMutation
cloneTemplateRepository requiredArgs object_ =
    Object.selectionForCompositeField "cloneTemplateRepository" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCloneTemplateRepositoryInput ] object_ (identity >> Decode.nullable)


type alias CloseIssueRequiredArguments =
    { input : Api.GitHub.InputObject.CloseIssueInput }


{-| Close an issue.
-}
closeIssue : CloseIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CloseIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
closeIssue requiredArgs object_ =
    Object.selectionForCompositeField "closeIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCloseIssueInput ] object_ (identity >> Decode.nullable)


type alias ClosePullRequestRequiredArguments =
    { input : Api.GitHub.InputObject.ClosePullRequestInput }


{-| Close a pull request.
-}
closePullRequest : ClosePullRequestRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ClosePullRequestPayload -> SelectionSet (Maybe decodesTo) RootMutation
closePullRequest requiredArgs object_ =
    Object.selectionForCompositeField "closePullRequest" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeClosePullRequestInput ] object_ (identity >> Decode.nullable)


type alias ConvertProjectCardNoteToIssueRequiredArguments =
    { input : Api.GitHub.InputObject.ConvertProjectCardNoteToIssueInput }


{-| Convert a project note card to one associated with a newly created issue.
-}
convertProjectCardNoteToIssue : ConvertProjectCardNoteToIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ConvertProjectCardNoteToIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
convertProjectCardNoteToIssue requiredArgs object_ =
    Object.selectionForCompositeField "convertProjectCardNoteToIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeConvertProjectCardNoteToIssueInput ] object_ (identity >> Decode.nullable)


type alias CreateBranchProtectionRuleRequiredArguments =
    { input : Api.GitHub.InputObject.CreateBranchProtectionRuleInput }


{-| Create a new branch protection rule
-}
createBranchProtectionRule : CreateBranchProtectionRuleRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateBranchProtectionRulePayload -> SelectionSet (Maybe decodesTo) RootMutation
createBranchProtectionRule requiredArgs object_ =
    Object.selectionForCompositeField "createBranchProtectionRule" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateBranchProtectionRuleInput ] object_ (identity >> Decode.nullable)


type alias CreateEnterpriseOrganizationRequiredArguments =
    { input : Api.GitHub.InputObject.CreateEnterpriseOrganizationInput }


{-| Creates an organization as part of an enterprise account.
-}
createEnterpriseOrganization : CreateEnterpriseOrganizationRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateEnterpriseOrganizationPayload -> SelectionSet (Maybe decodesTo) RootMutation
createEnterpriseOrganization requiredArgs object_ =
    Object.selectionForCompositeField "createEnterpriseOrganization" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateEnterpriseOrganizationInput ] object_ (identity >> Decode.nullable)


type alias CreateIssueRequiredArguments =
    { input : Api.GitHub.InputObject.CreateIssueInput }


{-| Creates a new issue.
-}
createIssue : CreateIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
createIssue requiredArgs object_ =
    Object.selectionForCompositeField "createIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateIssueInput ] object_ (identity >> Decode.nullable)


type alias CreateProjectRequiredArguments =
    { input : Api.GitHub.InputObject.CreateProjectInput }


{-| Creates a new project.
-}
createProject : CreateProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
createProject requiredArgs object_ =
    Object.selectionForCompositeField "createProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateProjectInput ] object_ (identity >> Decode.nullable)


type alias CreatePullRequestRequiredArguments =
    { input : Api.GitHub.InputObject.CreatePullRequestInput }


{-| Create a new pull request
-}
createPullRequest : CreatePullRequestRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreatePullRequestPayload -> SelectionSet (Maybe decodesTo) RootMutation
createPullRequest requiredArgs object_ =
    Object.selectionForCompositeField "createPullRequest" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreatePullRequestInput ] object_ (identity >> Decode.nullable)


type alias CreateRefRequiredArguments =
    { input : Api.GitHub.InputObject.CreateRefInput }


{-| Create a new Git Ref.
-}
createRef : CreateRefRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateRefPayload -> SelectionSet (Maybe decodesTo) RootMutation
createRef requiredArgs object_ =
    Object.selectionForCompositeField "createRef" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateRefInput ] object_ (identity >> Decode.nullable)


type alias CreateRepositoryRequiredArguments =
    { input : Api.GitHub.InputObject.CreateRepositoryInput }


{-| Create a new repository.
-}
createRepository : CreateRepositoryRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateRepositoryPayload -> SelectionSet (Maybe decodesTo) RootMutation
createRepository requiredArgs object_ =
    Object.selectionForCompositeField "createRepository" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateRepositoryInput ] object_ (identity >> Decode.nullable)


type alias CreateTeamDiscussionRequiredArguments =
    { input : Api.GitHub.InputObject.CreateTeamDiscussionInput }


{-| Creates a new team discussion.
-}
createTeamDiscussion : CreateTeamDiscussionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateTeamDiscussionPayload -> SelectionSet (Maybe decodesTo) RootMutation
createTeamDiscussion requiredArgs object_ =
    Object.selectionForCompositeField "createTeamDiscussion" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateTeamDiscussionInput ] object_ (identity >> Decode.nullable)


type alias CreateTeamDiscussionCommentRequiredArguments =
    { input : Api.GitHub.InputObject.CreateTeamDiscussionCommentInput }


{-| Creates a new team discussion comment.
-}
createTeamDiscussionComment : CreateTeamDiscussionCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.CreateTeamDiscussionCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
createTeamDiscussionComment requiredArgs object_ =
    Object.selectionForCompositeField "createTeamDiscussionComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeCreateTeamDiscussionCommentInput ] object_ (identity >> Decode.nullable)


type alias DeclineTopicSuggestionRequiredArguments =
    { input : Api.GitHub.InputObject.DeclineTopicSuggestionInput }


{-| Rejects a suggested topic for the repository.
-}
declineTopicSuggestion : DeclineTopicSuggestionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeclineTopicSuggestionPayload -> SelectionSet (Maybe decodesTo) RootMutation
declineTopicSuggestion requiredArgs object_ =
    Object.selectionForCompositeField "declineTopicSuggestion" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeclineTopicSuggestionInput ] object_ (identity >> Decode.nullable)


type alias DeleteBranchProtectionRuleRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteBranchProtectionRuleInput }


{-| Delete a branch protection rule
-}
deleteBranchProtectionRule : DeleteBranchProtectionRuleRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteBranchProtectionRulePayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteBranchProtectionRule requiredArgs object_ =
    Object.selectionForCompositeField "deleteBranchProtectionRule" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteBranchProtectionRuleInput ] object_ (identity >> Decode.nullable)


type alias DeleteIssueRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteIssueInput }


{-| Deletes an Issue object.
-}
deleteIssue : DeleteIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteIssue requiredArgs object_ =
    Object.selectionForCompositeField "deleteIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteIssueInput ] object_ (identity >> Decode.nullable)


type alias DeleteIssueCommentRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteIssueCommentInput }


{-| Deletes an IssueComment object.
-}
deleteIssueComment : DeleteIssueCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteIssueCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteIssueComment requiredArgs object_ =
    Object.selectionForCompositeField "deleteIssueComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteIssueCommentInput ] object_ (identity >> Decode.nullable)


type alias DeleteProjectRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteProjectInput }


{-| Deletes a project.
-}
deleteProject : DeleteProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteProject requiredArgs object_ =
    Object.selectionForCompositeField "deleteProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteProjectInput ] object_ (identity >> Decode.nullable)


type alias DeleteProjectCardRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteProjectCardInput }


{-| Deletes a project card.
-}
deleteProjectCard : DeleteProjectCardRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteProjectCardPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteProjectCard requiredArgs object_ =
    Object.selectionForCompositeField "deleteProjectCard" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteProjectCardInput ] object_ (identity >> Decode.nullable)


type alias DeleteProjectColumnRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteProjectColumnInput }


{-| Deletes a project column.
-}
deleteProjectColumn : DeleteProjectColumnRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteProjectColumnPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteProjectColumn requiredArgs object_ =
    Object.selectionForCompositeField "deleteProjectColumn" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteProjectColumnInput ] object_ (identity >> Decode.nullable)


type alias DeletePullRequestReviewRequiredArguments =
    { input : Api.GitHub.InputObject.DeletePullRequestReviewInput }


{-| Deletes a pull request review.
-}
deletePullRequestReview : DeletePullRequestReviewRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeletePullRequestReviewPayload -> SelectionSet (Maybe decodesTo) RootMutation
deletePullRequestReview requiredArgs object_ =
    Object.selectionForCompositeField "deletePullRequestReview" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeletePullRequestReviewInput ] object_ (identity >> Decode.nullable)


type alias DeletePullRequestReviewCommentRequiredArguments =
    { input : Api.GitHub.InputObject.DeletePullRequestReviewCommentInput }


{-| Deletes a pull request review comment.
-}
deletePullRequestReviewComment : DeletePullRequestReviewCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeletePullRequestReviewCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
deletePullRequestReviewComment requiredArgs object_ =
    Object.selectionForCompositeField "deletePullRequestReviewComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeletePullRequestReviewCommentInput ] object_ (identity >> Decode.nullable)


type alias DeleteRefRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteRefInput }


{-| Delete a Git Ref.
-}
deleteRef : DeleteRefRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteRefPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteRef requiredArgs object_ =
    Object.selectionForCompositeField "deleteRef" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteRefInput ] object_ (identity >> Decode.nullable)


type alias DeleteTeamDiscussionRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteTeamDiscussionInput }


{-| Deletes a team discussion.
-}
deleteTeamDiscussion : DeleteTeamDiscussionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteTeamDiscussionPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteTeamDiscussion requiredArgs object_ =
    Object.selectionForCompositeField "deleteTeamDiscussion" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteTeamDiscussionInput ] object_ (identity >> Decode.nullable)


type alias DeleteTeamDiscussionCommentRequiredArguments =
    { input : Api.GitHub.InputObject.DeleteTeamDiscussionCommentInput }


{-| Deletes a team discussion comment.
-}
deleteTeamDiscussionComment : DeleteTeamDiscussionCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DeleteTeamDiscussionCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteTeamDiscussionComment requiredArgs object_ =
    Object.selectionForCompositeField "deleteTeamDiscussionComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDeleteTeamDiscussionCommentInput ] object_ (identity >> Decode.nullable)


type alias DismissPullRequestReviewRequiredArguments =
    { input : Api.GitHub.InputObject.DismissPullRequestReviewInput }


{-| Dismisses an approved or rejected pull request review.
-}
dismissPullRequestReview : DismissPullRequestReviewRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.DismissPullRequestReviewPayload -> SelectionSet (Maybe decodesTo) RootMutation
dismissPullRequestReview requiredArgs object_ =
    Object.selectionForCompositeField "dismissPullRequestReview" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeDismissPullRequestReviewInput ] object_ (identity >> Decode.nullable)


type alias FollowUserRequiredArguments =
    { input : Api.GitHub.InputObject.FollowUserInput }


{-| Follow a user.
-}
followUser : FollowUserRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.FollowUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
followUser requiredArgs object_ =
    Object.selectionForCompositeField "followUser" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeFollowUserInput ] object_ (identity >> Decode.nullable)


type alias InviteEnterpriseAdminRequiredArguments =
    { input : Api.GitHub.InputObject.InviteEnterpriseAdminInput }


{-| Invite someone to become an administrator of the enterprise.
-}
inviteEnterpriseAdmin : InviteEnterpriseAdminRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.InviteEnterpriseAdminPayload -> SelectionSet (Maybe decodesTo) RootMutation
inviteEnterpriseAdmin requiredArgs object_ =
    Object.selectionForCompositeField "inviteEnterpriseAdmin" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeInviteEnterpriseAdminInput ] object_ (identity >> Decode.nullable)


type alias LinkRepositoryToProjectRequiredArguments =
    { input : Api.GitHub.InputObject.LinkRepositoryToProjectInput }


{-| Creates a repository link for a project.
-}
linkRepositoryToProject : LinkRepositoryToProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.LinkRepositoryToProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
linkRepositoryToProject requiredArgs object_ =
    Object.selectionForCompositeField "linkRepositoryToProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeLinkRepositoryToProjectInput ] object_ (identity >> Decode.nullable)


type alias LockLockableRequiredArguments =
    { input : Api.GitHub.InputObject.LockLockableInput }


{-| Lock a lockable object
-}
lockLockable : LockLockableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.LockLockablePayload -> SelectionSet (Maybe decodesTo) RootMutation
lockLockable requiredArgs object_ =
    Object.selectionForCompositeField "lockLockable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeLockLockableInput ] object_ (identity >> Decode.nullable)


type alias MergeBranchRequiredArguments =
    { input : Api.GitHub.InputObject.MergeBranchInput }


{-| Merge a head into a branch.
-}
mergeBranch : MergeBranchRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.MergeBranchPayload -> SelectionSet (Maybe decodesTo) RootMutation
mergeBranch requiredArgs object_ =
    Object.selectionForCompositeField "mergeBranch" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeMergeBranchInput ] object_ (identity >> Decode.nullable)


type alias MergePullRequestRequiredArguments =
    { input : Api.GitHub.InputObject.MergePullRequestInput }


{-| Merge a pull request.
-}
mergePullRequest : MergePullRequestRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.MergePullRequestPayload -> SelectionSet (Maybe decodesTo) RootMutation
mergePullRequest requiredArgs object_ =
    Object.selectionForCompositeField "mergePullRequest" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeMergePullRequestInput ] object_ (identity >> Decode.nullable)


type alias MoveProjectCardRequiredArguments =
    { input : Api.GitHub.InputObject.MoveProjectCardInput }


{-| Moves a project card to another place.
-}
moveProjectCard : MoveProjectCardRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.MoveProjectCardPayload -> SelectionSet (Maybe decodesTo) RootMutation
moveProjectCard requiredArgs object_ =
    Object.selectionForCompositeField "moveProjectCard" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeMoveProjectCardInput ] object_ (identity >> Decode.nullable)


type alias MoveProjectColumnRequiredArguments =
    { input : Api.GitHub.InputObject.MoveProjectColumnInput }


{-| Moves a project column to another place.
-}
moveProjectColumn : MoveProjectColumnRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.MoveProjectColumnPayload -> SelectionSet (Maybe decodesTo) RootMutation
moveProjectColumn requiredArgs object_ =
    Object.selectionForCompositeField "moveProjectColumn" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeMoveProjectColumnInput ] object_ (identity >> Decode.nullable)


type alias RegenerateEnterpriseIdentityProviderRecoveryCodesRequiredArguments =
    { input : Api.GitHub.InputObject.RegenerateEnterpriseIdentityProviderRecoveryCodesInput }


{-| Regenerates the identity provider recovery codes for an enterprise
-}
regenerateEnterpriseIdentityProviderRecoveryCodes : RegenerateEnterpriseIdentityProviderRecoveryCodesRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RegenerateEnterpriseIdentityProviderRecoveryCodesPayload -> SelectionSet (Maybe decodesTo) RootMutation
regenerateEnterpriseIdentityProviderRecoveryCodes requiredArgs object_ =
    Object.selectionForCompositeField "regenerateEnterpriseIdentityProviderRecoveryCodes" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRegenerateEnterpriseIdentityProviderRecoveryCodesInput ] object_ (identity >> Decode.nullable)


type alias RemoveAssigneesFromAssignableRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveAssigneesFromAssignableInput }


{-| Removes assignees from an assignable object.
-}
removeAssigneesFromAssignable : RemoveAssigneesFromAssignableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveAssigneesFromAssignablePayload -> SelectionSet (Maybe decodesTo) RootMutation
removeAssigneesFromAssignable requiredArgs object_ =
    Object.selectionForCompositeField "removeAssigneesFromAssignable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveAssigneesFromAssignableInput ] object_ (identity >> Decode.nullable)


type alias RemoveEnterpriseAdminRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveEnterpriseAdminInput }


{-| Removes an administrator from the enterprise.
-}
removeEnterpriseAdmin : RemoveEnterpriseAdminRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveEnterpriseAdminPayload -> SelectionSet (Maybe decodesTo) RootMutation
removeEnterpriseAdmin requiredArgs object_ =
    Object.selectionForCompositeField "removeEnterpriseAdmin" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveEnterpriseAdminInput ] object_ (identity >> Decode.nullable)


type alias RemoveEnterpriseOrganizationRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveEnterpriseOrganizationInput }


{-| Removes an organization from the enterprise
-}
removeEnterpriseOrganization : RemoveEnterpriseOrganizationRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveEnterpriseOrganizationPayload -> SelectionSet (Maybe decodesTo) RootMutation
removeEnterpriseOrganization requiredArgs object_ =
    Object.selectionForCompositeField "removeEnterpriseOrganization" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveEnterpriseOrganizationInput ] object_ (identity >> Decode.nullable)


type alias RemoveLabelsFromLabelableRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveLabelsFromLabelableInput }


{-| Removes labels from a Labelable object.
-}
removeLabelsFromLabelable : RemoveLabelsFromLabelableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveLabelsFromLabelablePayload -> SelectionSet (Maybe decodesTo) RootMutation
removeLabelsFromLabelable requiredArgs object_ =
    Object.selectionForCompositeField "removeLabelsFromLabelable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveLabelsFromLabelableInput ] object_ (identity >> Decode.nullable)


type alias RemoveOutsideCollaboratorRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveOutsideCollaboratorInput }


{-| Removes outside collaborator from all repositories in an organization.
-}
removeOutsideCollaborator : RemoveOutsideCollaboratorRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveOutsideCollaboratorPayload -> SelectionSet (Maybe decodesTo) RootMutation
removeOutsideCollaborator requiredArgs object_ =
    Object.selectionForCompositeField "removeOutsideCollaborator" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveOutsideCollaboratorInput ] object_ (identity >> Decode.nullable)


type alias RemoveReactionRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveReactionInput }


{-| Removes a reaction from a subject.
-}
removeReaction : RemoveReactionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveReactionPayload -> SelectionSet (Maybe decodesTo) RootMutation
removeReaction requiredArgs object_ =
    Object.selectionForCompositeField "removeReaction" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveReactionInput ] object_ (identity >> Decode.nullable)


type alias RemoveStarRequiredArguments =
    { input : Api.GitHub.InputObject.RemoveStarInput }


{-| Removes a star from a Starrable.
-}
removeStar : RemoveStarRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RemoveStarPayload -> SelectionSet (Maybe decodesTo) RootMutation
removeStar requiredArgs object_ =
    Object.selectionForCompositeField "removeStar" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRemoveStarInput ] object_ (identity >> Decode.nullable)


type alias ReopenIssueRequiredArguments =
    { input : Api.GitHub.InputObject.ReopenIssueInput }


{-| Reopen a issue.
-}
reopenIssue : ReopenIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ReopenIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
reopenIssue requiredArgs object_ =
    Object.selectionForCompositeField "reopenIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeReopenIssueInput ] object_ (identity >> Decode.nullable)


type alias ReopenPullRequestRequiredArguments =
    { input : Api.GitHub.InputObject.ReopenPullRequestInput }


{-| Reopen a pull request.
-}
reopenPullRequest : ReopenPullRequestRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ReopenPullRequestPayload -> SelectionSet (Maybe decodesTo) RootMutation
reopenPullRequest requiredArgs object_ =
    Object.selectionForCompositeField "reopenPullRequest" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeReopenPullRequestInput ] object_ (identity >> Decode.nullable)


type alias RequestReviewsRequiredArguments =
    { input : Api.GitHub.InputObject.RequestReviewsInput }


{-| Set review requests on a pull request.
-}
requestReviews : RequestReviewsRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.RequestReviewsPayload -> SelectionSet (Maybe decodesTo) RootMutation
requestReviews requiredArgs object_ =
    Object.selectionForCompositeField "requestReviews" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeRequestReviewsInput ] object_ (identity >> Decode.nullable)


type alias ResolveReviewThreadRequiredArguments =
    { input : Api.GitHub.InputObject.ResolveReviewThreadInput }


{-| Marks a review thread as resolved.
-}
resolveReviewThread : ResolveReviewThreadRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.ResolveReviewThreadPayload -> SelectionSet (Maybe decodesTo) RootMutation
resolveReviewThread requiredArgs object_ =
    Object.selectionForCompositeField "resolveReviewThread" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeResolveReviewThreadInput ] object_ (identity >> Decode.nullable)


type alias SubmitPullRequestReviewRequiredArguments =
    { input : Api.GitHub.InputObject.SubmitPullRequestReviewInput }


{-| Submits a pending pull request review.
-}
submitPullRequestReview : SubmitPullRequestReviewRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.SubmitPullRequestReviewPayload -> SelectionSet (Maybe decodesTo) RootMutation
submitPullRequestReview requiredArgs object_ =
    Object.selectionForCompositeField "submitPullRequestReview" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeSubmitPullRequestReviewInput ] object_ (identity >> Decode.nullable)


type alias TransferIssueRequiredArguments =
    { input : Api.GitHub.InputObject.TransferIssueInput }


{-| Transfer an issue to a different repository
-}
transferIssue : TransferIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.TransferIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
transferIssue requiredArgs object_ =
    Object.selectionForCompositeField "transferIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeTransferIssueInput ] object_ (identity >> Decode.nullable)


type alias UnarchiveRepositoryRequiredArguments =
    { input : Api.GitHub.InputObject.UnarchiveRepositoryInput }


{-| Unarchives a repository.
-}
unarchiveRepository : UnarchiveRepositoryRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnarchiveRepositoryPayload -> SelectionSet (Maybe decodesTo) RootMutation
unarchiveRepository requiredArgs object_ =
    Object.selectionForCompositeField "unarchiveRepository" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnarchiveRepositoryInput ] object_ (identity >> Decode.nullable)


type alias UnfollowUserRequiredArguments =
    { input : Api.GitHub.InputObject.UnfollowUserInput }


{-| Unfollow a user.
-}
unfollowUser : UnfollowUserRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnfollowUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
unfollowUser requiredArgs object_ =
    Object.selectionForCompositeField "unfollowUser" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnfollowUserInput ] object_ (identity >> Decode.nullable)


type alias UnlinkRepositoryFromProjectRequiredArguments =
    { input : Api.GitHub.InputObject.UnlinkRepositoryFromProjectInput }


{-| Deletes a repository link from a project.
-}
unlinkRepositoryFromProject : UnlinkRepositoryFromProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnlinkRepositoryFromProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
unlinkRepositoryFromProject requiredArgs object_ =
    Object.selectionForCompositeField "unlinkRepositoryFromProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnlinkRepositoryFromProjectInput ] object_ (identity >> Decode.nullable)


type alias UnlockLockableRequiredArguments =
    { input : Api.GitHub.InputObject.UnlockLockableInput }


{-| Unlock a lockable object
-}
unlockLockable : UnlockLockableRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnlockLockablePayload -> SelectionSet (Maybe decodesTo) RootMutation
unlockLockable requiredArgs object_ =
    Object.selectionForCompositeField "unlockLockable" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnlockLockableInput ] object_ (identity >> Decode.nullable)


type alias UnmarkIssueAsDuplicateRequiredArguments =
    { input : Api.GitHub.InputObject.UnmarkIssueAsDuplicateInput }


{-| Unmark an issue as a duplicate of another issue.
-}
unmarkIssueAsDuplicate : UnmarkIssueAsDuplicateRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnmarkIssueAsDuplicatePayload -> SelectionSet (Maybe decodesTo) RootMutation
unmarkIssueAsDuplicate requiredArgs object_ =
    Object.selectionForCompositeField "unmarkIssueAsDuplicate" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnmarkIssueAsDuplicateInput ] object_ (identity >> Decode.nullable)


type alias UnresolveReviewThreadRequiredArguments =
    { input : Api.GitHub.InputObject.UnresolveReviewThreadInput }


{-| Marks a review thread as unresolved.
-}
unresolveReviewThread : UnresolveReviewThreadRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UnresolveReviewThreadPayload -> SelectionSet (Maybe decodesTo) RootMutation
unresolveReviewThread requiredArgs object_ =
    Object.selectionForCompositeField "unresolveReviewThread" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUnresolveReviewThreadInput ] object_ (identity >> Decode.nullable)


type alias UpdateBranchProtectionRuleRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateBranchProtectionRuleInput }


{-| Create a new branch protection rule
-}
updateBranchProtectionRule : UpdateBranchProtectionRuleRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateBranchProtectionRulePayload -> SelectionSet (Maybe decodesTo) RootMutation
updateBranchProtectionRule requiredArgs object_ =
    Object.selectionForCompositeField "updateBranchProtectionRule" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateBranchProtectionRuleInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseActionExecutionCapabilitySettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseActionExecutionCapabilitySettingInput }


{-| Sets the action execution capability setting for an enterprise.
-}
updateEnterpriseActionExecutionCapabilitySetting : UpdateEnterpriseActionExecutionCapabilitySettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseActionExecutionCapabilitySettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseActionExecutionCapabilitySetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseActionExecutionCapabilitySetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseActionExecutionCapabilitySettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseAdministratorRoleRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseAdministratorRoleInput }


{-| Updates the role of an enterprise administrator.
-}
updateEnterpriseAdministratorRole : UpdateEnterpriseAdministratorRoleRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseAdministratorRolePayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseAdministratorRole requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseAdministratorRole" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseAdministratorRoleInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseAllowPrivateRepositoryForkingSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseAllowPrivateRepositoryForkingSettingInput }


{-| Sets whether private repository forks are enabled for an enterprise.
-}
updateEnterpriseAllowPrivateRepositoryForkingSetting : UpdateEnterpriseAllowPrivateRepositoryForkingSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseAllowPrivateRepositoryForkingSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseAllowPrivateRepositoryForkingSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseAllowPrivateRepositoryForkingSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseDefaultRepositoryPermissionSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseDefaultRepositoryPermissionSettingInput }


{-| Sets the default repository permission for organizations in an enterprise.
-}
updateEnterpriseDefaultRepositoryPermissionSetting : UpdateEnterpriseDefaultRepositoryPermissionSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseDefaultRepositoryPermissionSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseDefaultRepositoryPermissionSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseDefaultRepositoryPermissionSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseDefaultRepositoryPermissionSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput }


{-| Sets whether organization members with admin permissions on a repository can change repository visibility.
-}
updateEnterpriseMembersCanChangeRepositoryVisibilitySetting : UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanChangeRepositoryVisibilitySetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanChangeRepositoryVisibilitySetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanCreateRepositoriesSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanCreateRepositoriesSettingInput }


{-| Sets the members can create repositories setting for an enterprise.
-}
updateEnterpriseMembersCanCreateRepositoriesSetting : UpdateEnterpriseMembersCanCreateRepositoriesSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanCreateRepositoriesSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanCreateRepositoriesSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanCreateRepositoriesSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanDeleteIssuesSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanDeleteIssuesSettingInput }


{-| Sets the members can delete issues setting for an enterprise.
-}
updateEnterpriseMembersCanDeleteIssuesSetting : UpdateEnterpriseMembersCanDeleteIssuesSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanDeleteIssuesSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanDeleteIssuesSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanDeleteIssuesSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanDeleteIssuesSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanDeleteRepositoriesSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanDeleteRepositoriesSettingInput }


{-| Sets the members can delete repositories setting for an enterprise.
-}
updateEnterpriseMembersCanDeleteRepositoriesSetting : UpdateEnterpriseMembersCanDeleteRepositoriesSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanDeleteRepositoriesSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanDeleteRepositoriesSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanDeleteRepositoriesSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanInviteCollaboratorsSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanInviteCollaboratorsSettingInput }


{-| Sets whether members can invite collaborators are enabled for an enterprise.
-}
updateEnterpriseMembersCanInviteCollaboratorsSetting : UpdateEnterpriseMembersCanInviteCollaboratorsSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanInviteCollaboratorsSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanInviteCollaboratorsSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanInviteCollaboratorsSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanMakePurchasesSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanMakePurchasesSettingInput }


{-| Sets whether or not an organization admin can make purchases.
-}
updateEnterpriseMembersCanMakePurchasesSetting : UpdateEnterpriseMembersCanMakePurchasesSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanMakePurchasesSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanMakePurchasesSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanMakePurchasesSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanMakePurchasesSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingInput }


{-| Sets the members can update protected branches setting for an enterprise.
-}
updateEnterpriseMembersCanUpdateProtectedBranchesSetting : UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanUpdateProtectedBranchesSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanUpdateProtectedBranchesSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanUpdateProtectedBranchesSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseMembersCanViewDependencyInsightsSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseMembersCanViewDependencyInsightsSettingInput }


{-| Sets the members can view dependency insights for an enterprise.
-}
updateEnterpriseMembersCanViewDependencyInsightsSetting : UpdateEnterpriseMembersCanViewDependencyInsightsSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseMembersCanViewDependencyInsightsSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseMembersCanViewDependencyInsightsSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseMembersCanViewDependencyInsightsSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseOrganizationProjectsSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseOrganizationProjectsSettingInput }


{-| Sets whether organization projects are enabled for an enterprise.
-}
updateEnterpriseOrganizationProjectsSetting : UpdateEnterpriseOrganizationProjectsSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseOrganizationProjectsSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseOrganizationProjectsSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseOrganizationProjectsSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseOrganizationProjectsSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseProfileRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseProfileInput }


{-| Updates an enterprise's profile.
-}
updateEnterpriseProfile : UpdateEnterpriseProfileRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseProfilePayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseProfile requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseProfile" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseProfileInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseRepositoryProjectsSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseRepositoryProjectsSettingInput }


{-| Sets whether repository projects are enabled for a enterprise.
-}
updateEnterpriseRepositoryProjectsSetting : UpdateEnterpriseRepositoryProjectsSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseRepositoryProjectsSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseRepositoryProjectsSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseRepositoryProjectsSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseRepositoryProjectsSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseTeamDiscussionsSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseTeamDiscussionsSettingInput }


{-| Sets whether team discussions are enabled for an enterprise.
-}
updateEnterpriseTeamDiscussionsSetting : UpdateEnterpriseTeamDiscussionsSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseTeamDiscussionsSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseTeamDiscussionsSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseTeamDiscussionsSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseTeamDiscussionsSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateEnterpriseTwoFactorAuthenticationRequiredSettingRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput }


{-| Sets whether two factor authentication is required for all users in an enterprise.
-}
updateEnterpriseTwoFactorAuthenticationRequiredSetting : UpdateEnterpriseTwoFactorAuthenticationRequiredSettingRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateEnterpriseTwoFactorAuthenticationRequiredSetting requiredArgs object_ =
    Object.selectionForCompositeField "updateEnterpriseTwoFactorAuthenticationRequiredSetting" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput ] object_ (identity >> Decode.nullable)


type alias UpdateIssueRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateIssueInput }


{-| Updates an Issue.
-}
updateIssue : UpdateIssueRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateIssuePayload -> SelectionSet (Maybe decodesTo) RootMutation
updateIssue requiredArgs object_ =
    Object.selectionForCompositeField "updateIssue" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateIssueInput ] object_ (identity >> Decode.nullable)


type alias UpdateIssueCommentRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateIssueCommentInput }


{-| Updates an IssueComment object.
-}
updateIssueComment : UpdateIssueCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateIssueCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateIssueComment requiredArgs object_ =
    Object.selectionForCompositeField "updateIssueComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateIssueCommentInput ] object_ (identity >> Decode.nullable)


type alias UpdateProjectRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateProjectInput }


{-| Updates an existing project.
-}
updateProject : UpdateProjectRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateProjectPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateProject requiredArgs object_ =
    Object.selectionForCompositeField "updateProject" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateProjectInput ] object_ (identity >> Decode.nullable)


type alias UpdateProjectCardRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateProjectCardInput }


{-| Updates an existing project card.
-}
updateProjectCard : UpdateProjectCardRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateProjectCardPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateProjectCard requiredArgs object_ =
    Object.selectionForCompositeField "updateProjectCard" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateProjectCardInput ] object_ (identity >> Decode.nullable)


type alias UpdateProjectColumnRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateProjectColumnInput }


{-| Updates an existing project column.
-}
updateProjectColumn : UpdateProjectColumnRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateProjectColumnPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateProjectColumn requiredArgs object_ =
    Object.selectionForCompositeField "updateProjectColumn" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateProjectColumnInput ] object_ (identity >> Decode.nullable)


type alias UpdatePullRequestRequiredArguments =
    { input : Api.GitHub.InputObject.UpdatePullRequestInput }


{-| Update a pull request
-}
updatePullRequest : UpdatePullRequestRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdatePullRequestPayload -> SelectionSet (Maybe decodesTo) RootMutation
updatePullRequest requiredArgs object_ =
    Object.selectionForCompositeField "updatePullRequest" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdatePullRequestInput ] object_ (identity >> Decode.nullable)


type alias UpdatePullRequestReviewRequiredArguments =
    { input : Api.GitHub.InputObject.UpdatePullRequestReviewInput }


{-| Updates the body of a pull request review.
-}
updatePullRequestReview : UpdatePullRequestReviewRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdatePullRequestReviewPayload -> SelectionSet (Maybe decodesTo) RootMutation
updatePullRequestReview requiredArgs object_ =
    Object.selectionForCompositeField "updatePullRequestReview" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdatePullRequestReviewInput ] object_ (identity >> Decode.nullable)


type alias UpdatePullRequestReviewCommentRequiredArguments =
    { input : Api.GitHub.InputObject.UpdatePullRequestReviewCommentInput }


{-| Updates a pull request review comment.
-}
updatePullRequestReviewComment : UpdatePullRequestReviewCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdatePullRequestReviewCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
updatePullRequestReviewComment requiredArgs object_ =
    Object.selectionForCompositeField "updatePullRequestReviewComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdatePullRequestReviewCommentInput ] object_ (identity >> Decode.nullable)


type alias UpdateRefRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateRefInput }


{-| Update a Git Ref.
-}
updateRef : UpdateRefRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateRefPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateRef requiredArgs object_ =
    Object.selectionForCompositeField "updateRef" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateRefInput ] object_ (identity >> Decode.nullable)


type alias UpdateRepositoryRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateRepositoryInput }


{-| Update information about a repository.
-}
updateRepository : UpdateRepositoryRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateRepositoryPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateRepository requiredArgs object_ =
    Object.selectionForCompositeField "updateRepository" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateRepositoryInput ] object_ (identity >> Decode.nullable)


type alias UpdateSubscriptionRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateSubscriptionInput }


{-| Updates the state for subscribable subjects.
-}
updateSubscription : UpdateSubscriptionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateSubscriptionPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateSubscription requiredArgs object_ =
    Object.selectionForCompositeField "updateSubscription" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateSubscriptionInput ] object_ (identity >> Decode.nullable)


type alias UpdateTeamDiscussionRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateTeamDiscussionInput }


{-| Updates a team discussion.
-}
updateTeamDiscussion : UpdateTeamDiscussionRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateTeamDiscussionPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateTeamDiscussion requiredArgs object_ =
    Object.selectionForCompositeField "updateTeamDiscussion" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateTeamDiscussionInput ] object_ (identity >> Decode.nullable)


type alias UpdateTeamDiscussionCommentRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateTeamDiscussionCommentInput }


{-| Updates a discussion comment.
-}
updateTeamDiscussionComment : UpdateTeamDiscussionCommentRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateTeamDiscussionCommentPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateTeamDiscussionComment requiredArgs object_ =
    Object.selectionForCompositeField "updateTeamDiscussionComment" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateTeamDiscussionCommentInput ] object_ (identity >> Decode.nullable)


type alias UpdateTopicsRequiredArguments =
    { input : Api.GitHub.InputObject.UpdateTopicsInput }


{-| Replaces the repository's topics with the given topics.
-}
updateTopics : UpdateTopicsRequiredArguments -> SelectionSet decodesTo Api.GitHub.Object.UpdateTopicsPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateTopics requiredArgs object_ =
    Object.selectionForCompositeField "updateTopics" [ Argument.required "input" requiredArgs.input Api.GitHub.InputObject.encodeUpdateTopicsInput ] object_ (identity >> Decode.nullable)
