module VerifyExamples.Helper.Bool.Bool0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Helper.Bool exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#bool: \n\n    bool \"nope\" \"yes\" False\n    --> \"nope\"" <|
        \() ->
            Expect.equal
                (
                bool "nope" "yes" False
                )
                (
                "nope"
                )