module VerifyExamples.Helper.Bool.When1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Helper.Bool exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#when: \n\n    when True (String.reverse) \"yes\"\n    --> \"sey\"" <|
        \() ->
            Expect.equal
                (
                when True (String.reverse) "yes"
                )
                (
                "sey"
                )